[package]
name = "bmi323_scratch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# heapless = "0.8.0"
# linked_list_allocator = "0.10.5"
