[package]
name = "bmi323_scratch"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = { version = "0.3.8", optional = true }
embedded-hal = "1.0.0"
embedded-hal-mock = { version = "0.11.1", features = ["eh1"] }
